### ISSUE TITLE
Support mesos 0.25.0

### ISSUE THREAD

**Issue by F21** [mesos/elasticsearch#338]
In mesos 0.24.0, the mesos leader info in ZK has changed to json: https://issues.apache.org/jira/browse/MESOS-2340

When running the scheduler, it fails:

```
I0928 06:57:41.306650  4884 exec.cpp:133] Version: 0.24.0
I0928 06:57:41.322912  4885 exec.cpp:207] Executor registered on slave 20150928-051303-169978048-5050-596-S1
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tmp/elasticsearch-mesos-scheduler.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tmp/elasticsearch-mesos-scheduler.jar!/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2015-09-28 06:57:49,337:5(0x7fe2bbaf7700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-09-28 06:57:49,337:5(0x7fe2bbaf7700):ZOO_INFO@log_env@716: Client environment:host.name=core-02
2015-09-28 06:57:49,337:5(0x7fe2bbaf7700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-09-28 06:57:49,337:5(0x7fe2bbaf7700):ZOO_INFO@log_env@724: Client environment:os.arch=4.2.0-coreos-r1
2015-09-28 06:57:49,337:5(0x7fe2bbaf7700):ZOO_INFO@log_env@725: Client environment:os.version=#2 SMP Thu Sep 24 08:00:18 UTC 2015
2015-09-28 06:57:49,337:5(0x7fe2bbaf7700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2015-09-28 06:57:49,338:5(0x7fe2bbaf7700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-09-28 06:57:49,338:5(0x7fe2bbaf7700):ZOO_INFO@log_env@753: Client environment:user.dir=/
2015-09-28 06:57:49,338:5(0x7fe2bbaf7700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=master.mesos:2181 sessionTimeout=20000 watcher=0x7fe2bee35a60 sessionId=0 sessionPasswd=<null> context=0x209d310 flags=0
2015-09-28 06:57:49,343:5(0x7fe2b8ed1700):ZOO_INFO@check_events@1703: initiated connection to server [192.168.33.10:2181]
2015-09-28 06:57:49,348:5(0x7fe2b8ed1700):ZOO_INFO@check_events@1750: session establishment complete on server [192.168.33.10:2181], sessionId=0x150125f1c9c0702, negotiated timeout=20000
2015-09-28 06:57:49,361:5(0x7fe2ba2f4700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-09-28 06:57:49,361:5(0x7fe2ba2f4700):ZOO_INFO@log_env@716: Client environment:host.name=core-02
2015-09-28 06:57:49,361:5(0x7fe2ba2f4700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-09-28 06:57:49,361:5(0x7fe2ba2f4700):ZOO_INFO@log_env@724: Client environment:os.arch=4.2.0-coreos-r1
I0928 06:57:49.361845    20 sched.cpp:157] Version: 0.22.1
2015-09-28 06:57:49,361:5(0x7fe2ba2f4700):ZOO_INFO@log_env@725: Client environment:os.version=#2 SMP Thu Sep 24 08:00:18 UTC 2015
2015-09-28 06:57:49,362:5(0x7fe2ba2f4700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2015-09-28 06:57:49,362:5(0x7fe2ba2f4700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2015-09-28 06:57:49,362:5(0x7fe2ba2f4700):ZOO_INFO@log_env@753: Client environment:user.dir=/
2015-09-28 06:57:49,362:5(0x7fe2ba2f4700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=master.mesos:2181 sessionTimeout=10000 watcher=0x7fe2bee35a60 sessionId=0 sessionPasswd=<null> context=0x7fe288000b90 flags=0
2015-09-28 06:57:49,367:5(0x7fe2a77fe700):ZOO_INFO@check_events@1703: initiated connection to server [192.168.33.10:2181]
2015-09-28 06:57:49,386:5(0x7fe2a77fe700):ZOO_INFO@check_events@1750: session establishment complete on server [192.168.33.10:2181], sessionId=0x150125f1c9c0703, negotiated timeout=10000
I0928 06:57:49.387136    29 group.cpp:313] Group process (group(1)@192.168.33.11:41438) connected to ZooKeeper
I0928 06:57:49.387387    29 group.cpp:790] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0928 06:57:49.388294    29 group.cpp:385] Trying to create path '/mesos' in ZooKeeper
I0928 06:57:49.429330    29 detector.cpp:138] Detected a new leader: (id='2')
I0928 06:57:49.429570    29 group.cpp:659] Trying to get '/mesos/json.info_0000000002' in ZooKeeper
Failed to detect a master: Failed to parse data of unknown label 'json.info'
```

**Comment by F21** [comment]
Seeing the same issue on 0.24.1.

**Comment by tobilg** [comment]
+1

**Comment by odinxux** [comment]
+1

**Comment by dallasmarlow** [comment]
@F21 this is solved and verified to be functional by https://github.com/mesos/elasticsearch/pull/349

**Comment by F21** [comment]
Awesome! :fireworks:

**Comment by mwl** [comment]
Blocked. Waiting for ContainerSolutions/mini-mesos#87

**Comment by odinxux** [comment]
still not working ...

I1013 09:47:28.021571    40 group.cpp:313] Group process (group(1)@127.0.1.1:58876) connected to ZooKeeper
I1013 09:47:28.021600    40 group.cpp:790] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I1013 09:47:28.021615    40 group.cpp:385] Trying to create path '/mesos' in ZooKeeper
I1013 09:47:28.022953    38 detector.cpp:138] Detected a new leader: (id='5')
I1013 09:47:28.023108    34 group.cpp:659] Trying to get '/mesos/json.info_0000000005' in ZooKeeper
Failed to detect a master: Failed to parse data of unknown label 'json.info'

**Comment by a-nldisr** [comment]
Mesos 0.25 has been released today.

**Comment by frankscholten** [comment]
@mwl https://github.com/ContainerSolutions/mini-mesos/pull/87 is merged

**Comment by mwl** [comment]
I know. But I'm dealing with #311 which is failing on CI…

**Comment by mwl** [comment]
Fixed in #386

**Comment by tobilg** [comment]
Doesn't work for me using current `master`. I think it's because by standard, the `mesos/elasticsearch-executor:latest` image is pulled.

It should work when specifying `--executorImage mesos/elasticsearch-executor:snapshot` as argument.

**Comment by mwl** [comment]
When trying to run master, you'll always have to build it (including images) with `./gradlew clean build`
